name: 【手動実行】Qiita記事の最新版をとってきてGitHubに適用する

# 手動実行させる（記事を書いた後だとコンフリクトを起こすので、運用対処は必須）
on:
  workflow_dispatch:

# push時の権限を与える
permissions:
  contents: write

jobs:
  sync-qiita:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4

      - name: Qiitaの記事をとってくる。既に重複しているはずなので強制書き換えを付与
        run: |
          npm install
          npx qiita pull -f
        env:
          QIITA_TOKEN: ${{ secrets.QIITA_TOKEN }}

      - name: コミット＆プッシュ
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Sync Qiita articles"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
