name: Manual Qiita Sync

on:
  workflow_dispatch:
    inputs:
      reason:
        description: '実行理由'
        required: false
        default: '記事の同期'

jobs:
  sync-qiita:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install

      - name: Pull Qiita articles
        run: npx qiita pull
        env:
          QIITA_TOKEN: ${{ secrets.QIITA_TOKEN }}

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Sync Qiita articles"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
